spring:
    application:
        name: WetterKafka
    data:
        mongodb:
            database: "wetter"
            host: "${MONGO_INITDB_ROOT_HOST:localhost}"
            port: 27017
            username: "${MONGO_INITDB_ROOT_USERNAME:admin}"
            password: "${MONGO_INITDB_ROOT_PASSWORD:password}"

openweather:
    api-key: "${OPENWEATHER_API_KEY:replace-me-in-your-profile}"
    baseUrl: "http://api.openweathermap.org"
    weatherByGeolocationEndpoint: "/data/2.5/weather"
    geolocationByCityEndpoint: "/geo/1.0/direct"