services:

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: wetter
    volumes:
      - mongodb_data:/data/db
    networks:
      - wetter-network

    # TODO: kafka

volumes:
  mongodb_data:
    driver: local

networks:
  wetter-network:
    driver: bridge

